import { Inter } from 'next/font/google'
import Link from 'next/link'
// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    
    <html lang="en">
      <body className={inter.className}>
        <nav style={{ display: 'flex', flexDirection: 'row', gap: '10px' }}>
          <button><Link href="/">Home</Link></button>
          <button><Link href="/dashboard">DashBoard</Link></button>
          <button><Link href="/about">About</Link></button>
          <button><Link href="/contact">Contact</Link></button>
          <button><Link href="/users">Users</Link></button>
          <button><Link href="/parallelRoutes">Parallel Routes</Link></button>
          <button><Link href="/routeHandler">Routes Handler</Link></button>
          <button><Link href="/routeHandler/api">Routes Handler with cookies</Link></button>
          <button><Link href="/dashboardError">DashBoard Error</Link></button>
          <button><Link href="/serverComponent">server Component</Link></button>    
          <button><Link href="/static">Static Rendering</Link></button>    
          <button><Link href="/dynamic">Dynamic Rendering</Link></button>    
          <button><Link href="/generateStaticParams">Generate Static Params</Link></button>    
          
        </nav>
        {children}
      </body>
    </html>
  )
}
