

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout(props: {
  children: React.ReactNode;
  analytics: React.ReactNode;
  team: React.ReactNode;
}) {

  return (
    <>
      {props.children}
      <div style={{ display: 'flex', flexDirection: 'row', gap: '10px' }}>
        <div style={{ border: '1px solid black', height: '80px', width: '600px', textAlign: 'center' }}>
          {props.team}
        </div>
        <div style={{ border: '1px solid black', height: '80px', width: '600px', textAlign: 'center' }}>
          {props.analytics}
        </div>
      </div>
    </>
  )
}
